server:
  port: 8899

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Tann-chen/microservice-erp-configs
      label: master

security:
  user:
    name: devAdmin
    password: erp!@#ERP