version: '0'
services:
  config:
    image: config:v1
    ports:
      - "8899:8899"

  registry:
    image: registry:v1
    ports:
      - "8761:8761"

  authorize:
    image: authorize:v1
    ports:
      - "9000:9000"
    links:
      - "config:config"
      - "registry:registry"


  docker run -i --name gateway -p 8080:8080 --link config:config --link registry:registry --link biz-inventory:biz-inventory --link biz-user:biz-user --link authorize:authorize gateway:v1