spring:
  profiles:
    active: dev


---
spring:
  profiles: dev
  cloud:
    config:
      uri: http://localhost:8899
      fail-fast: true
      username: devAdmin
      password: erp!@#ERP
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    base-url: http://localhost:9411

  datasource:
    url: jdbc:mysql://erpdb.ch7napik4dgs.us-east-2.rds.amazonaws.com:3306/erpdb?useUnicode=true&characterEncoding=utf-8&&useSSL=false
    username: admin
    password: adminroot
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


---
spring:
  profiles: test
  cloud:
    config:
      uri: http://config:8899
      fail-fast: true
      username: devAdmin
      password: erp!@#ERP

  datasource:
    url: jdbc:mysql://erpdb.ch7napik4dgs.us-east-2.rds.amazonaws.com:3306/erpdb?useUnicode=true&characterEncoding=utf-8&&useSSL=false
    username: admin
    password: adminroot
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: false

eureka:
  instance:
    hostname: biz-user
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://registry:8761/eureka/



