spring:
  profiles:
    active: dev


---
spring:
  profiles: dev
  cloud:
    config:
      uri: http://localhost:8899
      fail-fast: true
      username: devAdmin
      password: erp!@#ERP

eureka:
  instance:
      hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/
  server:
    enable-self-preservation: false


---
spring:
  profiles: test
  cloud:
    config:
      uri: http://registry:8899
      fail-fast: true
      username: devAdmin
      password: erp!@#ERP

eureka:
  instance:
    hostname: registry
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://registry:${server.port}/eureka/
  server:
    enable-self-preservation: false