server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://erpdb.ch7napik4dgs.us-east-2.rds.amazonaws.com:3306/erpdb?useUnicode=true&characterEncoding=utf-8&&useSSL=false
    username: admin
    password: adminroot
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
